## Matrix Inverse Method

In [1]:
import numpy as np

def find_sol_inverse(A, b):
    return np.linalg.inv(A).dot(b)

In [2]:
find_sol_inverse(np.array([[1, 1, -1], [2, -1, 1], [-1, 2, 2]]), np.array([-2, 5, 1]))

array([ 1., -1.,  2.])

## Gauss Elimination Method

In [3]:
# Importing NumPy Library
import numpy as np
import sys

def gauss_method(a):
    print(a)
    n = 3

    # Making numpy array of n size and initializing 
    # to zero for storing solution vector
    x = np.zeros(n)

    # Applying Gauss Elimination
    for i in range(n):
        if a[i][i] == 0.0:
            sys.exit('Divide by zero detected!')
            
        for j in range(i+1, n):
            ratio = a[j][i]/a[i][i]
            
            for k in range(n+1):
                a[j][k] = a[j][k] - ratio * a[i][k]

    # Back Substitution
    x[n-1] = a[n-1][n]/a[n-1][n-1]

    for i in range(n-2,-1,-1):
        x[i] = a[i][n]
        
        for j in range(i+1,n):
            x[i] = x[i] - a[i][j]*x[j]
        
        x[i] = x[i]/a[i][i]

    # Displaying solution
    print('\nRequired solution is: ')
    for i in range(n):
        print('X%d = %0.2f' %(i,x[i]), end = '\t')

In [4]:
a = np.array([[1., 1., -1., -2.], [2., -1., 1., 5.], [-1., 2., 2., 1.]])
gauss_method(a)

[[ 1.  1. -1. -2.]
 [ 2. -1.  1.  5.]
 [-1.  2.  2.  1.]]

Required solution is: 
X0 = 1.00	X1 = -1.00	X2 = 2.00	

## LU Decomposition Method

In [5]:
import numpy as np
from scipy.linalg import lu

def lud(A):
    L, U = lu(A, True)

    print("L: \n", L)
    print("U: \n", U)

    # Multiply L and U
    LU = np.dot(L, U)

    print("LU: \n", LU)
    print("A: \n", A)

    # Check if A and LU are equal within a tolerance
    if np.allclose(A, LU):
        print("LU decomposition is valid")
    else:
        print("LU decomposition is not valid")

In [6]:
A = np.array([[1, 1, -1], [2, -1, 1], [-1, 2, 2]])

lud(A)

L: 
 [[ 0.5  1.   0. ]
 [ 1.   0.   0. ]
 [-0.5  1.   1. ]]
U: 
 [[ 2.  -1.   1. ]
 [ 0.   1.5 -1.5]
 [ 0.   0.   4. ]]
LU: 
 [[ 1.  1. -1.]
 [ 2. -1.  1.]
 [-1.  2.  2.]]
A: 
 [[ 1  1 -1]
 [ 2 -1  1]
 [-1  2  2]]
LU decomposition is valid
